version: "3.8"
networks:
  db:
  mail:

x-app: &app
  build:
   context: .
   args:
     POETRY_ARGS: " "
  restart: unless-stopped
  env_file:
   - .env
  environment:
   - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
   - PORT=8000
  volumes:
   - .:/app
  networks:
   - db
   - mail
  depends_on:
   - postgres

services:
  postgres:
   image: postgres:13.2-alpine
   env_file:
     - .env
   networks:
     - db
   ports:
     - 5432:5432
   healthcheck:
     test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER" ]
     interval: 5s
     timeout: 5s
     retries: 5

  mailhog:
   image: mailhog/mailhog:v1.0.1
   ports:
     - 8025:8025
   networks:
     - mail

  hermes:
    <<: *app
    ports:
     - 8000:8000

  qcluster:
    <<: *app
    command: python /app/manage.py qcluster