# Generated by Django 3.1.7 on 2021-05-01 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="validate_referrer",
            field=models.BooleanField(default=True),
        ),
    ]
