# Generated by Django 3.1.7 on 2021-05-01 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0002_form_validate_referrer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="site",
            old_name="domain",
            new_name="url",
        ),
    ]
