# Generated by Django 3.1.7 on 2021-05-01 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms", "0003_auto_20210501_1339"),
    ]

    operations = [
        migrations.AddField(
            model_name="form",
            name="redirect_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
