# Generated by Django 3.1.7 on 2021-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="formmailsettings",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
    ]
